apiVersion: v1
kind: Service
metadata:
  name: sql-mysql-master
  labels:
    app: sql-mysql-master
spec:
  type: NodePort 
  ports:
    # the port that this service should serve on
  - name: mysql-native 
    port: 3306 
    targetPort: 3306
  selector:
    app: sql-mysql-master
