apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  type: NodePort 
  ports:
    # the port that this service should serve on
  - name: zookeeper-native
    port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
