apiVersion: v1
kind: Service
metadata:
  name: prediction-ensemble
  labels:
    app: prediction-ensemble
#      dns: route53
#    annotations:
#      domainName: prediction-python3.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: http-model-server
    port: 80
    targetPort: 9876
  - name: prometheus
    port: 8080
    targetPort: 8080
  selector:    
    app: prediction-ensemble
