apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prediction-ensemble
  labels:
    name: prediction-ensemble
    app: prediction-ensemble
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: prediction-ensemble
  template:
    metadata:
      labels:
        app: prediction-ensemble
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: prediction-ensemble
        image: docker.io/fluxcapacitor/prediction-python3:master
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi 
        imagePullPolicy: "Always"
        env:
        - name: PIO_MODEL_TYPE
          value: ensemble
        - name: PIO_MODEL_NAMESPACE
          value: default
        - name: PIO_MODEL_NAME
          value: ensemble_scikit_tensorflow_linear
        - name: PIO_MODEL_VERSION
          value: v0
        ports:
        - containerPort: 9876
        - containerPort: 8080
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml.git"
            revision: "master"
