apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prediction-tensorflow-gpu
  labels:
    app: prediction-tensorflow-gpu
    hystrix.enabled: "true"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: prediction-tensorflow-gpu
  template:
    metadata:
      labels:
        app: prediction-tensorflow-gpu
        hystrix.enabled: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "9040"
    spec:
      containers:
      - name: prediction-tensorflow-gpu
        image: docker.io/fluxcapacitor/prediction-tensorflow-gpu:master
        resources:
          limits:
            cpu: 3000m
            memory: 3000Mi
          requests:
            cpu: 300m
            memory: 100Mi 
        imagePullPolicy: "Always"
        env:
        - name: PIO_MODEL_TYPE
          value: tensorflow
        - name: PIO_MODEL_NAMESPACE
          value: default
        - name: PIO_MODEL_NAME
          value: tensorflow_linear 
        # Note:  For now, this must be an integer value.
        - name: PIO_MODEL_VERSION
          value: "0"
        ports:
        - containerPort: 9040
        - containerPort: 9876
        - containerPort: 9000
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml.git"
            revision: "master"
