apiVersion: v1
kind: Service
metadata:
  name: prediction-xgboost
  labels:
    app: prediction-xgboost
    hystrix.enabled: "true"
#    dns: route53
#  annotations:
#    domainName: "prediction-xgboost.your.domain.com"
spec:
  type: LoadBalancer
  ports:
  - name: prediction-xgboost
    port: 80 
    targetPort: 9040 
  selector:
    app: prediction-xgboost
    hystrix.enabled: "true" 
