apiVersion: v1
kind: Service
metadata:
  name: kafka-0-10
  labels:
    app: kafka-0-10 
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - name: native-kafka
    port: 9092
    targetPort: 9092
  - name: schema-registry
    port: 8081
    targetPort: 8081
  - name: rest-proxy
    port: 8082
    targetPort: 8082
  selector:
    app: kafka-0-10
