apiVersion: v1
kind: Service
metadata:
  name: presto-master 
  labels:
    app: presto-master
spec:
  type: NodePort 
  ports:
  - name: presto-native
    port: 7060 
    targetPort: 7060
  selector:
    app: presto-master
