apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: presto-worker
  labels:
    app: presto-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presto-worker
  template:
    metadata:
      labels:
        app: presto-worker
    spec:
      containers:
      - name: presto-worker
        image: docker.io/fluxcapacitor/presto-worker-0.167:master
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 7060
#        volumeMounts:
#          - name: hadoop-conf-dev-volume
#            mountPath: /etc/hadoop/conf/dev
#          - name: hadoop-conf-prod-volume
#            mountPath: /etc/hadoop/conf/prod
#      volumes:
#        - name: hadoop-conf-dev-volume
#          secret:
#            secretName: hadoop-conf-dev
#        - name: hadoop-conf-prod-volume
#          secret:
#            secretName: hadoop-conf-prod
