apiVersion: v1
kind: Service
metadata:
  name: presto-worker
  labels:
    app: presto-worker
spec:
  type: NodePort
  ports:
  - name: presto-native
    port: 7060 
    targetPort: 7060
  selector:
    app: presto-worker
