apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-5-0-0 
  labels:
    app: elasticsearch-5-0-0
#    dns: route53
#  annotations:
#    domainName: "elasticsearch.your.domain.com"
spec:
  type: NodePort 
  ports:
  - name: native 
    port: 9200 
    targetPort: 9200 
  - name: "9300" 
    port: 9300
    targetPort: 9300
  selector:
    app: elasticsearch-5-0-0
