apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs-namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-namenode
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      containers:
      - name: hdfs-namenode
        image: docker.io/fluxcapacitor/hdfs-namenode:master
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 8000
        - containerPort: 9000
        - containerPort: 50070
        volumeMounts:
#          - name: hadoop-conf-dev-volume
#            mountPath: /etc/hadoop/conf
          - name: git-volume
            mountPath: /root/volumes
      volumes:
#        - name: hadoop-conf-dev-volume
#          secret:
#            secretName: hadoop-conf-dev
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml"
            revision: "master"
