apiVersion: v1
kind: Service
metadata:
  name: clustered-tensorflow-ps0 
  labels:
    job_name: ps
spec:
  type: LoadBalancer
  ports:
  - name: native-tensorflow 
    port: 2222
    targetPort: 2222
  selector:
    name: clustered-tensorflow-ps0
