apiVersion: v1
kind: ReplicationController
metadata:
  name: clustered-tensorflow-ps
  labels:
    app: clustered-tensorflow-ps
spec:
  replicas: 1
  selector:
    name: clustered-tensorflow-ps
  template:
    metadata:
      labels:
        name: clustered-tensorflow-ps
    spec:
      containers:
      - name: clustered-tensorflow-ps
        image: docker.io/fluxcapacitor/clustered-tensorflow:master
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: PS_HOSTS
          value: clustered-tensorflow-ps:2222
        - name: WORKER_HOSTS
          value: clustered-tensorflow-worker:2222
        - name: JOB_NAME
          value: ps
        - name: TASK_INDEX
          value: "0"
        ports:
        - containerPort: 2222
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml.git"
            revision: "master"
