apiVersion: v1
kind: Service
metadata:
  name: clustered-tensorflow-worker0 
  labels:
    job_name: worker 
spec:
  type: LoadBalancer
  ports:
  - name: native-tensorflow
    port: 2222
    targetPort: 2222
  selector:
    name: clustered-tensorflow-worker0
