apiVersion: v1
kind: Service
metadata:
  name: kibana-4-5-0
  labels:
    app: kibana-4-5-0
#    dns: route53
#  annotations:
#    domainName: "kibana.your.domain.com"
spec:
  type: LoadBalancer 
  ports:
  - name: http 
    port: 80 
    targetPort: 5601 
  selector:
    app: kibana-4-5-0
