apiVersion: v1
kind: Service
metadata:
  name: web-sparkafterdark
  labels:
    app: web-sparkafterdark
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: web-sparkafterdark
