apiVersion: v1
kind: Service
metadata:
  name: zeppelin
  labels:
    app: zeppelin
#    dns: route53
#  annotations:
#    domainName: zeppelin.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80 
    targetPort: 3123 
  - name: "websocket"
    port: 81 
    targetPort: 3124
  selector:
    app: zeppelin
